import re
from typing import Dict

def parse_llm_output(text: str) -> Dict[str, str]:
    """
    Parses the raw text output from the LLM to extract actionable commands or the final answer.
    
    Args:
        text (str): The raw string generated by the Groq API.
        
    Returns:
        Dict[str, str]: A structured dictionary containing the parsed state.
                        Keys typically include 'type' (action/final/error), 
                        'tool', 'arg', or 'content'.
    """

    final_answer_pattern = r"Final Answer:\s*(.*)"
    final_match = re.search(final_answer_pattern, text, re.DOTALL | re.IGNORECASE)

    if final_match:
        return{
            "type": "final",
            "content": final_match.group(1).strip()
        }

    action_pattern = r"Action:\s*calculate\[(.*?)\]"
    action_match = re.search(action_pattern, text, re.IGNORECASE)

    if action_match:
        return {
            "type": "action",
            "tool": "calculate",
            "arg": action_match.group(1).strip()
        }

    return {
        "type": "error",
        "content": "syntax error: Unable to parse the LLM output. Please ensure the output follows the expected format."
    }